#!/usr/bin/env bash

# File @generated by hack/generate-authors.sh. DO NOT EDIT.
# This file lists all contributors to the repository.
# See hack/generate-authors.sh to make modifications.

echo "$comment" > AUTHORS


git log --format-'%aN <%aE>' | sort -u | sed -e 's/^/-/' >>AUTHORS